experimental_monorepo_root = true

[env]
MISE_EXPERIMENTAL = true

[monorepo]
config_roots = [
    "backend",
    "docker",
    "frontend"
]

[tools]
rust = "1.92.0"
node = "22.21.1"
pnpm = "10.27.0"

[tasks.backend]
depends = [
    "//docker:surrealdb-start",
    "//docker:redis-start",
]
run = "mise run //backend:run"
depends_post = [
    "//docker:surrealdb-stop",
    "//docker:redis-stop",
]

[tasks.frontend]
depends = [
    "//frontend:install"
]
run = "mise run //frontend:run"
