experimental_monorepo_root = true

[env]
MISE_EXPERIMENTAL = true

[monorepo]
config_roots = [
    "backend",
    "deployment/docker",
]

[tools]
rust = "1.94.1"
node = "24.14.0"
pnpm = "10.32.1"

[tasks.start-all]
run = "mise run //deployment/docker:start-all"

[tasks.stop-all]
run = "mise run //deployment/docker:stop-all"

[tasks.start-infrastructure]
run = "mise run //deployment/docker:start-infrastructure"

[tasks.stop-infrastructure]
run = "mise run //deployment/docker:stop-infrastructure"
