[tasks."start-all"]
run = '''
# Start all
./docker-compose-all.sh up --build -d
'''

[tasks."stop-all"]
run = '''
# Stop all
./docker-compose-all.sh down
'''

[tasks."start-infrastructure"]
run = '''
# Start infrastructure
./docker-compose-infrastructure.sh up --build -d
'''

[tasks."stop-infrastructure"]
run = '''
# Stop infrastructure
./docker-compose-infrastructure.sh down
'''
