[tasks."start-infrastructure"]
run = ["./docker-compose-infrastructure.sh up --build -d"]

[tasks."stop-infrastructure"]
run = [
  "./docker-compose-infrastructure.sh down",
  "rm -rf postgres",
  "rm -rf redis",
]
